// <auto-generated />
namespace Proyecto_Final_de_lenguaje_de_programacion_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class primaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primaria));
        
        string IMigrationMetadata.Id
        {
            get { return "202208082358544_primaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
