// <auto-generated />
namespace Proyecto_Final_de_lenguaje_de_programacion_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateinpuestoentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateinpuestoentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171916188_update-in-puesto-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
